apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: qotd-git
  namespace: pipelines-tutorial
spec:
  params:
    - name: url
      value: 'https://github.com/donschenck/qotd-python.git'
  type: git
